api:
  # Existing parameters
  name: "meta-llama/Llama-4-Scout-17B-16E-Instruct"
  temperature: 0.1
  max_tokens: 500
  max_retries: 3
  request_timeout: 30  # Increased for rate limiting
  qps_limit: 70        
  rpm_limit: 4400      
  tps_limit: 15000     
  batch_size: 300      

# Log
wandb:
  project: "vagen_process_reward_judge"
  run_name: "llm_judge"
  correct_grounding_samples: 8
  incorrect_grounding_samples: 8
  correct_worldmodeling_samples: 8
  incorrect_worldmodeling_samples: 8
  parse_failed_samples: 8
  table_logging_frequency: 10

# Prompt
prompt_templates:
  # Default environment templates that other environments can reference
  default_env:
    grounding: |
      Compare the description of the current state with the groundtruth current state information.
      Answer YES if the description matches the current state information, or NO if it doesn't.

      # Context
      You are evaluating whether an agent's description accurately reflects the actual state. The description must be both correct overall AND specifically relevant to the important elements of the current state. Generic observations (like "player, box and target is on the ground") that don't capture the meaningful relationships and positions in the state are insufficient. The description should demonstrate understanding of the specific configuration and relationships that matter for decision-making.

      # Groundtruth Current State Information:
      {state_information_dict}

      # State Description:
      {natural_language_description}

      Think step by step and end with your answer.
      Your answer should be within {max_tokens} tokens and in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.
    worldmodeling: |
      Compare the prediction of the next state with the groundtruth next state information.
      Answer YES if the prediction accurately matches the next state information, or NO if it doesn't.

      # Context
      You are evaluating whether an agent's prediction of the next state is accurate. The prediction must be both correct overall AND specifically relevant to the important elements of the next state. Generic predictions that don't capture the meaningful changes, relationships, and positions in the state are insufficient. The prediction should demonstrate understanding of the specific configuration and relationships that will result from the action, showing how the state will transform in ways that matter for decision-making.

      # Groundtruth Next State Information:
      {state_information_dict}

      # Next State Prediction:
      {natural_language_description}

      Think step by step and end with your answer.
      Your answer should be within {max_tokens} tokens and in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.
  sokoban:
    grounding: |
      Evaluate whether the description accurately captures the key position relationships in the Sokoban game state.
      Answer YES if the directional relationships are correct, or NO if they contain directional errors.

      # Context
      You are evaluating whether the description correctly identifies the directional relationships between:
      1. The player and the box(es)
      2. The box(es) and the target(s)

      The description doesn't need to be perfectly precise or mention every detail - it just needs to have the correct directional relationships (Up, Down, Left, Right). 

      # How to interpret coordinates:
      - If comparing coordinates (row1, col1) and (row2, col2):
        - If row1 < row2: The first object is ABOVE the second object
        - If row1 > row2: The first object is BELOW the second object
        - If col1 < col2: The first object is to the LEFT of the second object
        - If col1 > col2: The first object is to the RIGHT of the second object
      
      Example: If player is at (3,2) and box is at (2,4):
      - Since 3 > 2, player is BELOW the box
      - Since 2 < 4, player is to the LEFT of the box
      - Correct description: "The box is Up and Right of the player" or "The Player is Down and Left of the box"

      # Groundtruth Current State Information:
      {state_information_dict}

      # State Description:
      {natural_language_description}

      Think step by step:
      1. Identify the coordinates of player, box(es), and target(s) from the state information
      2. Determine the correct directional relationships based on coordinate comparison
      3. Check if the description mentions these directional relationships correctly

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.

    worldmodeling: |
      Evaluate whether the prediction correctly anticipates the key position relationships that will exist in the next Sokoban state.
      Answer YES if the predicted directional relationships are correct, or NO if they contain directional errors.

      # Context
      You are evaluating whether the prediction correctly identifies the directional relationships that will exist after the move:
      1. The future position of the player relative to the box(es)
      2. The future position of the box(es) relative to the target(s)

      The prediction doesn't need to be perfectly precise or mention every detail - it just needs to correctly anticipate the directional relationships (Up, Down, Left, Right) that will exist after the move.

      # How to interpret coordinates:
      - If comparing coordinates (row1, col1) and (row2, col2):
        - If row1 < row2: The first object is ABOVE the second object
        - If row1 > row2: The first object is BELOW the second object
        - If col1 < col2: The first object is to the LEFT of the second object
        - If col1 > col2: The first object is to the RIGHT of the second object
      
      Example: If after the move, player will be at (3,2) and box will be at (2,4):
      - Since 3 > 2, player will be BELOW the box
      - Since 2 < 4, player will be to the LEFT of the box
      - Correct prediction: "After my move, the box will be Up and Right of me" or "I will be positioned Down and Left of the box"

      # Groundtruth Next State Information:
      {state_information_dict}

      # Next State Prediction:
      {natural_language_description}

      Think step by step:
      1. Identify the coordinates of player, box(es), and target(s) that will exist in the next state
      2. Determine the correct directional relationships based on coordinate comparison
      3. Check if the prediction mentions these directional relationships correctly

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.
  
  frozenlake:
    grounding: |
      Evaluate whether the description accurately captures the key position relationships in the FrozenLake game state.
      Answer YES if the directional relationships are correct and any relevant holes are mentioned, or NO if there are errors.

      # Context
      You are evaluating whether the description correctly identifies:
      1. The directional relationship between the player and the goal
      2. Any holes that are in the direct path between player and goal (if applicable)

      The description doesn't need to be perfectly precise - it just needs to have the correct directional relationships (Up, Down, Left, Right) and mention any critical holes that would block a direct path.

      # How to interpret coordinates:
      - If comparing coordinates (row1, col1) and (row2, col2):
        - If row1 < row2: The first object is ABOVE the second object
        - If row1 > row2: The first object is BELOW the second object
        - If col1 < col2: The first object is to the LEFT of the second object
        - If col1 > col2: The first object is to the RIGHT of the second object
      
      Example: If player is at (1,1) and goal is at (3,2):
      - Since 1 < 3, player is ABOVE the goal
      - Since 1 < 2, player is to the LEFT of the goal
      - Correct description: "The goal is Down and Right of the player"

      If there's a hole at (2,1) directly between player and goal, the description should mention this obstacle.

      # Groundtruth Current State Information:
      {state_information_dict}

      # State Description:
      {natural_language_description}

      Think step by step:
      1. Identify the coordinates of player and goal from the state information
      2. Determine the correct directional relationship based on coordinate comparison
      3. Check if there are any holes directly in the path between player and goal
      4. Verify if the description mentions the correct directional relationship
      5. Verify if the description acknowledges any critical holes in the path (if they exist)

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.

    worldmodeling: |
      Evaluate whether the prediction correctly anticipates the key aspects of the next FrozenLake state.
      Answer YES if the prediction accounts for directional relationships and potential holes, or NO if it contains errors.

      # Context
      You are evaluating whether the prediction correctly identifies:
      1. The future position relationship between the player and the goal after the move
      2. Whether the planned movement path avoids holes or acknowledges the risk of falling

      The prediction doesn't need to perfectly describe every aspect of the next state - it just needs to correctly anticipate the directional relationships (Up, Down, Left, Right) and address any dangers from holes.

      # How to interpret coordinates:
      - If comparing coordinates (row1, col1) and (row2, col2):
        - If row1 < row2: The first object is ABOVE the second object
        - If row1 > row2: The first object is BELOW the second object
        - If col1 < col2: The first object is to the LEFT of the second object
        - If col1 > col2: The first object is to the RIGHT of the second object
      
      Example: If after the move, player will be at (2,2) and goal is at (3,3):
      - Since 2 < 3, player will be ABOVE the goal
      - Since 2 < 3, player will be to the LEFT of the goal
      - Correct prediction: "After my move, the goal will be Down and Right of me"

      If there's a hole in the planned path, the prediction should acknowledge this risk.

      # CRITICAL: If the prediction suggests a path that would go directly through a hole, the answer should be NO.

      # Groundtruth Next State Information:
      {state_information_dict}

      # Next State Prediction:
      {natural_language_description}

      Think step by step:
      1. Identify the coordinates of player and goal in the next state
      2. Determine the correct directional relationship based on coordinate comparison
      3. Check if the planned movement path would encounter any holes
      4. Verify if the prediction mentions the correct directional relationship
      5. Verify if the prediction recognizes any risks from holes in the planned path
      6. If the prediction suggests moving through a hole, the answer must be NO

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.
  
  maniskill:
    grounding: |
      Compare the description of the current state with the groundtruth current state information.
      Answer YES if the description reasonably matches the current state information, or NO if it doesn't.

      # Context
      You are evaluating whether an agent's description accurately reflects the actual state. The description should capture the meaningful relationships and positions relevant for decision-making in the task.
      
      Important evaluation criteria:
      1. If the description includes coordinates, they don't need to be exact matches with the groundtruth
      2. For coordinate values, consider them correct if they are within these error tolerances:
        - For x and y coordinates: within ±10 units of groundtruth
        - For z coordinates: within ±10 units of groundtruth
      3. The overall spatial relationships and object identifications should be correct
      4. If the description includes a dict-formatted state information, that's good but not required

      # Groundtruth Current State Information:
      {state_information_dict}

      # State Description:
      {natural_language_description}

      Think step by step:
      1. Identify the key objects and their positions in the groundtruth information
      2. Check if the description correctly identifies these objects
      3. For any coordinates mentioned, check if they are within the acceptable error range
      4. Determine if the overall spatial understanding is correct, even if specific numbers differ slightly
      5. If coordinates in the description differ from groundtruth but are within the error tolerance, consider them correct

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.

    worldmodeling: |
      Compare the prediction of the next state with the groundtruth next state information.
      Answer YES if the prediction reasonably matches the next state information, or NO if it doesn't.

      # Context
      You are evaluating whether an agent's prediction of the next state is accurate. The prediction should capture the meaningful changes and relationships that will result from the planned actions.
      
      Important evaluation criteria:
      1. If the prediction includes coordinates, they don't need to be exact matches with the groundtruth
      2. For coordinate values, consider them correct if they are within these error tolerances:
        - For x and y coordinates: within ±10 units of groundtruth
        - For z coordinates: within ±10 units of groundtruth
      3. The overall predicted movements and resulting spatial relationships should be correct
      4. If the prediction includes a dict-formatted state information, that's good but not required

      # Groundtruth Next State Information:
      {state_information_dict}

      # Next State Prediction:
      {natural_language_description}

      Think step by step:
      1. Identify the key objects and their positions in the groundtruth next state information
      2. Check if the prediction correctly anticipates these object positions
      3. For any coordinates mentioned, check if they are within the acceptable error range
      4. Determine if the overall predicted movement and resulting state is correct, even if specific numbers differ slightly
      5. If coordinates in the prediction differ from groundtruth but are within the error tolerance, consider them correct

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.
  
  navigation:
    grounding: |
      Evaluate whether the description effectively communicates the spatial relationship between the agent and target object, even if the exact directional terms differ.
      Answer YES if the overall spatial understanding is correct, or NO if it fundamentally misunderstands the spatial layout.

      # Context
      You are evaluating whether the description effectively conveys where the target object is located relative to the agent. The exact directional terminology (left, right, ahead, etc.) may differ between the state information and the description, but the important factor is whether the description would lead to correct navigation.

      # Key evaluation principle:
      Even if the directional terms don't exactly match (e.g., state says "ahead" but description says "left"), consider the description CORRECT if:
      1. It describes other landmarks or objects that are in the same general direction as the target
      2. It correctly describes the relative positions between multiple objects, showing spatial awareness
      3. It would still lead to appropriate navigation actions to reach the target

      # Groundtruth Current State Information:
      {state_information_dict}

      # State Description:
      {natural_language_description}

      Think step by step:
      1. Identify where the target object is located relative to the agent from the state information
      2. Look at what other objects or landmarks are mentioned in both the state information and the description
      3. Check if the description correctly relates these objects/landmarks to each other spatially
      4. Determine if following the spatial understanding in the description would reasonably lead to the target, regardless of exact terminology used
      5. If the description mentions moving in a direction that would approximately lead toward the target, consider this correct even if the exact terms differ

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.

    worldmodeling: |
      Evaluate whether the prediction effectively anticipates how the agent would navigate toward the target object, even if the exact directional terms differ.
      Answer YES if the overall navigation plan is reasonable, or NO if it fundamentally misunderstands the spatial layout.

      # Context
      You are evaluating whether the prediction effectively anticipates how the agent would move to reach the target object. The exact directional terminology (left, right, ahead, etc.) may differ between the state information and the prediction, but the important factor is whether the prediction would lead to successful navigation.

      # Key evaluation principle:
      Even if the directional terms don't exactly match (e.g., state says "ahead" but prediction says "left"), consider the prediction CORRECT if:
      1. It describes a movement path that would generally lead toward the target
      2. It correctly anticipates how landmarks or objects would be positioned after movement
      3. The overall navigation strategy would plausibly succeed in reaching the target

      # Groundtruth Next State Information:
      {state_information_dict}

      # Next State Prediction:
      {natural_language_description}

      Think step by step:
      1. Identify the planned movements and where the target object would be located after these movements
      2. Look at what other objects or landmarks are mentioned in both the state information and the prediction
      3. Check if the prediction correctly anticipates how these objects/landmarks would be positioned relative to each other after movement
      4. Determine if the navigation strategy described would plausibly lead toward the target
      5. If the prediction mentions future positions or movements that would approximately lead toward the target, consider this correct even if the exact terms differ

      Your answer should be in the format of <think>...</think><answer>YES</answer> or <think>...</think><answer>NO</answer>.